// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9XPt4BKWXq3G2BUor2DEmubydTUy9i5Q',
    appId: '1:515041923871:web:7f493ac8c5c19cfbce962a',
    messagingSenderId: '515041923871',
    projectId: 'flutterfire-ui-codelab-35d83',
    authDomain: 'flutterfire-ui-codelab-35d83.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-35d83.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwmWRPzioOy26HDxUnjNOfZEP1H5vQk_w',
    appId: '1:515041923871:android:92665fdc7bb4366bce962a',
    messagingSenderId: '515041923871',
    projectId: 'flutterfire-ui-codelab-35d83',
    storageBucket: 'flutterfire-ui-codelab-35d83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7bUI5TEl5eS8GRfwh50wRBqZgb75EvXA',
    appId: '1:515041923871:ios:5b7f1edb6b8e96e1ce962a',
    messagingSenderId: '515041923871',
    projectId: 'flutterfire-ui-codelab-35d83',
    storageBucket: 'flutterfire-ui-codelab-35d83.firebasestorage.app',
    iosBundleId: 'com.example.digitPresence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7bUI5TEl5eS8GRfwh50wRBqZgb75EvXA',
    appId: '1:515041923871:ios:5b7f1edb6b8e96e1ce962a',
    messagingSenderId: '515041923871',
    projectId: 'flutterfire-ui-codelab-35d83',
    storageBucket: 'flutterfire-ui-codelab-35d83.firebasestorage.app',
    iosBundleId: 'com.example.digitPresence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9XPt4BKWXq3G2BUor2DEmubydTUy9i5Q',
    appId: '1:515041923871:web:46c782008d0be949ce962a',
    messagingSenderId: '515041923871',
    projectId: 'flutterfire-ui-codelab-35d83',
    authDomain: 'flutterfire-ui-codelab-35d83.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-35d83.firebasestorage.app',
  );
}
